#!/bin/bash

if [ "x$HIVE_HOME" == "x" ]; then
  export HIVE_HOME="/usr/local/hive-0.11.0-shark-SNAPSHOT-bin"
fi

if [ "x$HADOOP_HOME" == "x" ]; then
  export HADOOP_HOME="/usr/local/hadoop-1.0.3"
fi

# Add Hive jars.
for jar in `find $HIVE_HOME/lib -name '*jar'`; do
    JDBCC_CLASSPATH+=:$jar
done

for jar in `find $HADOOP_HOME/lib -name '*jar'`; do
    JDBCC_CLASSPATH+=:$jar
done
for jar in `find $HADOOP_HOME -name '*jar'`; do
    JDBCC_CLASSPATH+=:$jar
done


export JDBCC_CLASSPATH
export CLASSPATH+=$JDBCC_CLASSPATH 

if [ -n "$JAVA_HOME" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  RUNNER=java
fi

echo $CLASSPATH

exec $RUNNER -cp target/jdbc-client-1.jar:$CLASSPATH org.x4444.jdbcc "$@"
